### ISSUE TITLE
support case-insensitive search

### ISSUE THREAD

**Issue by abias** [marxjohnson/moodle-block_quickcourselist#4]
Hi,

sorry for double-posting, but I don't know if you are subscribed to Moodle Tracker.

Please have a look at http://tracker.moodle.org/browse/CONTRIB-3570

Thanks in advance
Alex

**Comment by marxjohnson** [comment]
I don't think this is going to be possible to support this in the plugin due to the way the search works. If the database uses a case-insensitive collation then the queries for search would always be case insensitive, which could be a workaround if this is required.
