### ISSUE TITLE
Allow for multi term searches

### ISSUE THREAD

**Issue by chadberg** [marxjohnson/moodle-block_quickcourselist#6]
The search box at the bottom of the course listings currently allows me to search by multiple terms, so I can search by more than one part of the short name, such as the department designation and the term designation.  It looks like this block only allows for exact single string searches at current.

**Comment by marxjohnson** [comment]
Thanks for the suggestion! It should be possible to split terms by spaces to build separate LIKE conditions joined by ANDs, meaning that a search for "Maths 101" would match the shortname "Unit 101 Maths" but not "Unit 102 Maths" or "Unit 101 English".

I'm not actively developing this plugin at the moment, but next time I'm working on it I'll look at implementing this.  If anyone wants to give it a shot on the mean time, I'd welcome the contribution!
