### ISSUE TITLE
Moodle 3.0.2

### ISSUE THREAD

**Issue by DrFlo** [marxjohnson/moodle-block_quickcourselist#9]
Tried to install the current version on Moodle 3.0.2+ (Build: 20160225), Ubuntu 14.04 LTS

These are the error messages spawning, hope it helps while developing a newer version

Plugin mod_quickcourselist does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

Invalid get_string() identifier: 'modulename' or component 'mod_quickcourselist'. Perhaps you are missing $string['modulename'] = ''; in mod/quickcourselist/lang/en/quickcourselist.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 6676 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 64 of /lib/classes/plugininfo/mod.php: call to get_string()
line 142 of /lib/classes/plugininfo/base.php: call to core\plugininfo\mod->init_display_name()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

Debug info: 
Error code: detectedmisplacedplugin
Stack trace:
line 631 of /lib/upgradelib.php: plugin_misplaced_exception thrown
line 427 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1641 of /lib/upgradelib.php: call to upgrade_plugins()
line 677 of /admin/index.php: call to upgrade_noncore()

Thank you for all the great work :)

**Comment by DrFlo** [comment]
I'm a complete an utter idiot, tried to install it through mods rather than a block

works perfectly fine ! 

Thank you and sorry

**Comment by marxjohnson** [comment]
That's great news, thanks! I'll add 3.0 as a supported version in the plugins database.
